[package]
categories.workspace   = true
description            = "Arrow compliance service GRPC server"
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license-file.workspace = true
name                   = "svc-compliance"
repository.workspace   = true
version                = "0.1.1-develop.0"

[features]
vendored-openssl = ['openssl/vendored']

[dependencies]
anyhow       = "1.0"
cargo-husky  = "1"
chrono       = { version = "0.4", features = ["serde"] }
config       = "0.13"
dotenv       = "0.15"
hyper        = "0.14"
log          = "0.4"
openssl      = "0.10"
prost        = "0.11"
prost-build  = "0.11"
prost-types  = "0.11"
serde        = "1.0"
serde_json   = "1.0"
tokio        = { version = "1.20", features = ["full"] }
tokio-util   = "0.7"
tonic        = "0.8"
tonic-health = "0.7"

[dependencies.log4rs]
features = [
  "background_rotation",
  "rolling_file_appender",
  "json_format",
  "gzip",
]
version = "1.2"

[dev-dependencies.cargo-husky]
default-features = false          # Disable features which are enabled by default
features         = ["user-hooks"]
version          = "1"

[build-dependencies]
tonic-build = "0.8"
