[package]
categories.workspace   = true
description            = "Arrow template service GRPC client"
edition.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
license-file.workspace = true
name                   = "svc-compliance-client-grpc"
repository.workspace   = true
version                = "0.1.1-develop.0"

[dependencies]
prost       = "0.11"
prost-types = "0.11"
tonic       = "0.8"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "grpc"
